services:
  db:
    image: postgres:14
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
  superset:
    build: .
    image: custom-superset:latest
    container_name: superset
    restart: unless-stopped
    depends_on:
    - db
    ports:
    - "8088:8088"
    environment:
      # SQLAlchemy connection string pointing at the "db" service
      SUPERSET_DATABASE_URI: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}"
    volumes:
      - superset_home:/app/superset_home
      - ./superset_config.py:/app/pythonpath/superset_config.py


volumes:
  pgdata:
  superset_home: